name: Test iOS Plugin Build

on:
  workflow_dispatch: 

jobs:
  build_ios:
    runs-on: macos-latest

    steps:
      - name: Descargar el código del plugin
        uses: actions/checkout@v4

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Descargar dependencias del ejemplo
        run: |
          cd example
          flutter pub get

      - name: Compilar app de ejemplo para iOS
        run: |
          cd example
          # Compilamos específicamente para el simulador
          flutter build ios --no-codesign --simulator

      - name: Subir la App de Ejemplo (Artifact)
        uses: actions/upload-artifact@v4
        with:
          name: App-Ejemplo-iOS
          # Esta es la ruta estándar donde Flutter deja el ejecutable del simulador
          path: example/build/ios/iphonesimulator/Runner.app
          # Opcional: Si Appetize te pide un .zip, puedes comprimirlo antes o
          # simplemente subir la carpeta .app y GitHub la zipeará automáticamente.